version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-container
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Isha2002!
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql
